### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by char** [Jordin/deltoid#5]
deltoid (aka JordinJMath) is a FOSS Java library focused on assisting your math and physics needs.

deltoid did not assist my math and physics needs

**Comment by Trol1337** [comment]
i vouch
i am not able to use it to calculate whats 1+1 and use a factory to send me the result back as a graph

**Comment by Jordin** [comment]
please submit your problem and our elite squad of mathematicians and physicists will start planning a solution immediately.

**Comment by char** [comment]
sorry i figured it out thank you
